// =============================================================================
// Seed Script — Populate cai_courses, cai_modules, cai_lessons from catalog
// Run: npx tsx scripts/seed-courses.ts
// =============================================================================

import { createClient } from '@supabase/supabase-js'
import { COURSE_CATALOG } from '../src/lib/course-catalog'

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL || ''
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_KEY || ''

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_KEY')
  process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY)

async function seed() {
  console.log(`Seeding ${COURSE_CATALOG.length} courses...`)

  for (const course of COURSE_CATALOG) {
    // Upsert course
    const { data: courseRow, error: courseErr } = await supabase
      .from('cai_courses')
      .upsert({
        slug: course.slug,
        title: course.title,
        credential_code: course.credential_code,
        description: course.description,
        prerequisites: course.prerequisites,
        difficulty: course.difficulty,
        estimated_hours: course.estimated_hours,
        module_count: course.modules.length,
        lesson_count: course.modules.reduce((s, m) => s + m.lessons.length, 0),
        metadata: { color: course.color },
        is_published: true,
        sort_order: course.sort_order,
      }, { onConflict: 'slug' })
      .select('id')
      .single()

    if (courseErr) {
      console.error(`  ERROR course ${course.slug}:`, courseErr.message)
      continue
    }
    console.log(`  Course: ${course.title} (${courseRow.id})`)

    for (const mod of course.modules) {
      // Upsert module
      const { data: modRow, error: modErr } = await supabase
        .from('cai_modules')
        .upsert({
          course_id: courseRow.id,
          slug: mod.slug,
          title: mod.title,
          description: mod.description,
          module_number: mod.module_number,
          lesson_count: mod.lessons.length,
          metadata: mod.metadata,
          is_published: true,
        }, { onConflict: 'course_id,slug' })
        .select('id')
        .single()

      if (modErr) {
        console.error(`    ERROR module ${mod.slug}:`, modErr.message)
        continue
      }
      console.log(`    Module ${mod.module_number}: ${mod.title} (${modRow.id})`)

      for (const lesson of mod.lessons) {
        const { error: lessonErr } = await supabase
          .from('cai_lessons')
          .upsert({
            module_id: modRow.id,
            slug: lesson.slug,
            title: lesson.title,
            content_markdown: '', // Generated by DAX later
            estimated_minutes: lesson.estimated_minutes,
            sort_order: lesson.sort_order,
            is_published: false, // Published after content generation
          }, { onConflict: 'module_id,slug' })

        if (lessonErr) {
          console.error(`      ERROR lesson ${lesson.slug}:`, lessonErr.message)
        }
      }
      console.log(`      ${mod.lessons.length} lessons seeded`)
    }
  }

  // Seed achievements from gamification definitions
  console.log('\nSeeding achievements...')
  const { ACHIEVEMENTS } = await import('../src/lib/gamification')

  for (const achievement of ACHIEVEMENTS) {
    const { error } = await supabase
      .from('cai_achievements')
      .upsert({
        slug: achievement.slug,
        title: achievement.title,
        description: achievement.description,
        icon: achievement.icon,
        xp_reward: achievement.xp_reward,
        rarity: achievement.rarity,
        category: achievement.category,
        criteria: { type: 'auto', slug: achievement.slug },
        is_active: true,
      }, { onConflict: 'slug' })

    if (error) {
      console.error(`  ERROR achievement ${achievement.slug}:`, error.message)
    }
  }
  console.log(`  ${ACHIEVEMENTS.length} achievements seeded`)

  console.log('\nDone!')
}

seed().catch(console.error)
